# diz ao Jekyll onde estão os arquivos especiais
layouts_dir: plantillas
includes_dir: partes

title: Me Llamo Llama
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
theme: null
exclude:
  - node_modules
  - vendor
